### ISSUE TITLE
enhance flush functionality (-F)

### ISSUE THREAD

**Issue by jlin-nf** [netfoundry/zfw#58]
Before we have egress filter, the -F flushes the ingress rules.  It still only flushed the ingress rules. To flush the egress rules, another optional parameter needs to be supplied: -z egress.

Please enhance this functionality to the following:

1.  -F only, will flush both ingress and egress rules.
2.  -F -z ingress, flushes ingress rules only (currently working correctly)
3. -F -z egress, flushes egress rules only (currently working correctly).

**Comment by r-caamano** [comment]
The requested logic change was added in v0.8.5
