### ISSUE TITLE
Enhance output of outbound filter command (-b)

### ISSUE THREAD

**Issue by jlin-nf** [netfoundry/zfw#59]
Enable outbound filter: zfw -b <interface name> does nothing if the tc filter for outbound is not enabled on that interface.

However, the command is successfully turn on the outbound filter setting (can see this by using  zfw -L -E). So it give user a false impression that the outbound filtering is on.

the -b command should return unsuccessful if tc filter is not turned on  already.

At the minimal, the command should yield a warning stating that tc filter needs to be turned on for the filter to function correctly.

**Comment by r-caamano** [comment]
Fix was added to v0.8.5 that denies completion of ```sudo zfw -b, --outbound-filter <interface name>``` if an egress tc filter does not exist on the interface.
