### ISSUE TITLE
Suppress error output when setting tc filter 

### ISSUE THREAD

**Issue by jlin-nf** [netfoundry/zfw#60]
$ sudo zfw -X ens33 -O /opt/openziti/bin/zfw_tc_outbound_track.o -z egress
Error: Exclusivity flag on, cannot modify.
tc parent already exists : ens33
Set tc filter enable to 1 for egress on ens33

when setting the filter the second time, enabling tc failed (already enabled).  but the setting of filter is successful. The error message (Error: Exclusivity flag on, cannot modify.) should be suppressed.

**Comment by r-caamano** [comment]
Note error was due to zfw attempting to add a parent clsact qdisc to the interface when one already exists.  Fix was added to v0.8.5 which checks to see if the parent exist before attempting to add one.
